openapi: '3.0.3'
info:
  title: API Stub
  description: おためし
  version: '0.0.1'
servers:
  - url: http://localhost:8080/v1
tags:
  - name: User
paths:
  /user:
    get:
      tags:
        - User
      summary: List Users
      operationId: getUsers
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
  /user/{userId}:
    get:
      tags:
        - User
      summary: Find user by ID
      operationId: getUserById
      parameters:
        - name: userId
          in: path
          description: ID of user to return
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
            application/xml:
              schema:
                $ref: '#/components/schemas/User'
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int32
          example: 10
        firstName:
          type: string
          description: First Name
          example: Hiroyuki
        lastName:
          type: string
          description: Last Name
          example: Fujie
      xml:
        name: user
